;;; py-execute-region-commandp-test.el --- Test execute region forms

;; URL: https://gitlab.com/python-mode-devs
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from python-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:

(ert-deftest py-execute-region-commandp-test-g4jSXk ()
  (should (commandp 'py-execute-region)))

(ert-deftest py-execute-region-dedicated-commandp-test-xjNPtU ()
  (should (commandp 'py-execute-region-dedicated)))

(ert-deftest py-ert-execute-region-python-commandp-test-mzriCL ()
  (should (commandp 'py-execute-region-python)))

(ert-deftest py-ert-execute-region-python-dedicated-commandp-test-n2l8Rk ()
  (should (commandp 'py-execute-region-python-dedicated)))

(ert-deftest py-ert-execute-region-python2-commandp-test-Yu8rSb ()
  (should (commandp 'py-execute-region-python2)))

(ert-deftest py-ert-execute-region-python2-dedicated-commandp-test-5IZGJK ()
  (should (commandp 'py-execute-region-python2-dedicated)))

(ert-deftest py-ert-execute-region-python3-commandp-test-YUa0DB ()
  (should (commandp 'py-execute-region-python3)))

(ert-deftest py-ert-execute-region-python3-dedicated-commandp-test-r8bz99 ()
  (should (commandp 'py-execute-region-python3-dedicated)))

(ert-deftest py-ert-execute-region-ipython-commandp-test-i3uGX0 ()
  (should (commandp 'py-execute-region-ipython)))

(ert-deftest py-ert-execute-region-ipython-dedicated-commandp-test-buWchz ()
  (should (commandp 'py-execute-region-ipython-dedicated)))

(ert-deftest py-ert-execute-region-ipython3-commandp-test-2yrvuU ()
  (should (commandp 'py-execute-region-ipython3)))

(ert-deftest py-ert-execute-region-ipython3-dedicated-commandp-test-VzBZLv ()
  (should (commandp 'py-execute-region-ipython3-dedicated)))

(ert-deftest py-ert-execute-region-jython-commandp-test-8HNOqn ()
  (should (commandp 'py-execute-region-jython)))

(ert-deftest py-ert-execute-region-jython-dedicated-commandp-test-HKVyeY ()
  (should (commandp 'py-execute-region-jython-dedicated)))

(provide 'py-execute-region-commandp-test)
;;; py-execute-region-commandp-test.el ends here
