;;; py-ert-beginning-tests.el --- Just some more tests 

;; Copyright (C) 2011-2014  Andreas Roehler
;; Author: Andreas Roehler <andreas.roehler@online.de>
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from python-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:


(ert-deftest py-ert-block-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (forward-line -3) 
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (py-beginning-of-block)
    (should (eq (char-after) ?f))))

(ert-deftest py-ert-clause-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (forward-line -3) 
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (py-beginning-of-clause)
    (should (eq (char-after) ?f))))

(ert-deftest py-ert-block-or-clause-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (forward-line -3) 
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (py-beginning-of-block-or-clause)
    (should (eq (char-after) ?f))))

(ert-deftest py-ert-def-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (forward-line -3) 
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (py-beginning-of-def)
    (should (eq (char-after) ?d))))

(ert-deftest py-ert-class-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (forward-line -3) 
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (py-beginning-of-class)
    (should (eq (char-after) ?c))))

(ert-deftest py-ert-def-or-class-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (forward-line -3) 
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (py-beginning-of-def-or-class)
    (should (eq (char-after) ?d))))

(ert-deftest py-ert-if-block-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (forward-line -3) 
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (py-beginning-of-if-block)
    (should (eq (char-after) ?i))))

(ert-deftest py-ert-try-block-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (forward-line -3) 
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (py-beginning-of-try-block)
    (should (eq (char-after) ?t))))

(ert-deftest py-ert-minor-block-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (forward-line -3) 
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (py-beginning-of-minor-block)
    (should (eq (char-after) ?f))))

(ert-deftest py-ert-for-block-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (forward-line -3) 
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (py-beginning-of-for-block)
    (should (eq (char-after) ?f))))

(ert-deftest py-ert-block-bol-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (forward-line -3) 
    (py-beginning-of-block-bol)
    (should (eq (char-after) ? ))))

(ert-deftest py-ert-clause-bol-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (forward-line -3) 
    (py-beginning-of-clause-bol)
    (should (eq (char-after) ? ))))

(ert-deftest py-ert-block-or-clause-bol-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (forward-line -3) 
    (py-beginning-of-block-or-clause-bol)
    (should (eq (char-after) ? ))))

(ert-deftest py-ert-def-bol-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (forward-line -3) 
    (py-beginning-of-def-bol)
    (should (eq (char-after) ? ))))

(ert-deftest py-ert-class-bol-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (forward-line -3) 
    (py-beginning-of-class-bol)
    (should (eq (char-after) ?c))))

(ert-deftest py-ert-def-or-class-bol-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (forward-line -3) 
    (py-beginning-of-def-or-class-bol)
    (should (eq (char-after) ? ))))

(ert-deftest py-ert-if-block-bol-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (forward-line -3) 
    (py-beginning-of-if-block-bol)
    (should (eq (char-after) ? ))))

(ert-deftest py-ert-try-block-bol-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (forward-line -3) 
    (py-beginning-of-try-block-bol)
    (should (eq (char-after) ? ))))

(ert-deftest py-ert-minor-block-bol-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (forward-line -3) 
    (py-beginning-of-minor-block-bol)
    (should (eq (char-after) ? ))))

(ert-deftest py-ert-for-block-bol-test ()
  (py-test-with-temp-buffer
      "
# -*- coding: utf-8 -*-
class bar:
  def foo ():
        try:
            if True:
                for a in b:
                    pass
        except:
            block2
"
    (when py-debug-p (switch-to-buffer (current-buffer))
          (font-lock-fontify-buffer))
    (forward-line -3) 
    (py-beginning-of-for-block-bol)
    (should (eq (char-after) ? ))))
(provide 'py-ert-beginning-tests)

;; py-ert-beginning-tests.el ends here
