;;; python-components-forward-forms.el -- Go to the end of forms -*- lexical-binding: t; -*-

;;This file is generated by function from python-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;; Copyright (C) 2015-2016 Andreas Röhler

;; Author: Andreas Röhler <andreas.roehler@online.de>
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from python-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:

(defun py-forward-region ()
  "Go to the end of current region."
  (interactive)
  (let ((end (region-end)))
    (when end (goto-char end))))

(defun py-forward-block ()
  "Go to end of block.

Return end of ‘block’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-block-re)))

(defun py-forward-block-bol ()
  "Goto beginning of line following end of ‘block’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-block’: down from current definition to next beginning of ‘block’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-block)))

(defun py-forward-block-or-clause ()
  "Go to end of block-or-clause.

Return end of ‘block-or-clause’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-block-or-clause-re)))

(defun py-forward-block-or-clause-bol ()
  "Goto beginning of line following end of ‘block-or-clause’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-block-or-clause’: down from current definition to next beginning of ‘block-or-clause’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-block-or-clause)))

;;;###autoload
(defun py-forward-class ()
  "Go to end of class.

Return end of ‘class’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-class-re)))

(defun py-forward-class-bol ()
  "Goto beginning of line following end of ‘class’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-class’: down from current definition to next beginning of ‘class’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-class)))

(defun py-forward-clause ()
  "Go to end of clause.

Return end of ‘clause’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-clause-re)))

(defun py-forward-clause-bol ()
  "Goto beginning of line following end of ‘clause’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-clause’: down from current definition to next beginning of ‘clause’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-clause)))

;;;###autoload
(defun py-forward-def ()
  "Go to end of def.

Return end of ‘def’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-def-re)))

(defun py-forward-def-bol ()
  "Goto beginning of line following end of ‘def’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-def’: down from current definition to next beginning of ‘def’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-def)))

;;;###autoload
(defun py-forward-def-or-class ()
  "Go to end of def-or-class.

Return end of ‘def-or-class’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-def-or-class-re)))

(defun py-forward-def-or-class-bol ()
  "Goto beginning of line following end of ‘def-or-class’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-def-or-class’: down from current definition to next beginning of ‘def-or-class’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-def-or-class)))

(defun py-forward-elif-block ()
  "Go to end of elif-block.

Return end of ‘elif-block’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-elif-re)))

(defun py-forward-elif-block-bol ()
  "Goto beginning of line following end of ‘elif-block’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-elif-block’: down from current definition to next beginning of ‘elif-block’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-elif-block)))

(defun py-forward-else-block ()
  "Go to end of else-block.

Return end of ‘else-block’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-else-re)))

(defun py-forward-else-block-bol ()
  "Goto beginning of line following end of ‘else-block’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-else-block’: down from current definition to next beginning of ‘else-block’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-else-block)))

(defun py-forward-except-block ()
  "Go to end of except-block.

Return end of ‘except-block’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-except-re)))

(defun py-forward-except-block-bol ()
  "Goto beginning of line following end of ‘except-block’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-except-block’: down from current definition to next beginning of ‘except-block’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-except-block)))

(defun py-forward-for-block ()
  "Go to end of for-block.

Return end of ‘for-block’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-for-re)))

(defun py-forward-for-block-bol ()
  "Goto beginning of line following end of ‘for-block’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-for-block’: down from current definition to next beginning of ‘for-block’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-for-block)))

(defun py-forward-if-block ()
  "Go to end of if-block.

Return end of ‘if-block’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-if-re)))

(defun py-forward-if-block-bol ()
  "Goto beginning of line following end of ‘if-block’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-if-block’: down from current definition to next beginning of ‘if-block’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-if-block)))

(defun py-forward-minor-block ()
  "Go to end of minor-block.

Return end of ‘minor-block’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-minor-block-re)))

(defun py-forward-minor-block-bol ()
  "Goto beginning of line following end of ‘minor-block’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-minor-block’: down from current definition to next beginning of ‘minor-block’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-minor-block)))

(defun py-forward-try-block ()
  "Go to end of try-block.

Return end of ‘try-block’ if successful, nil otherwise"
  (interactive)
  (cdr-safe (py--end-base 'py-try-re)))

(defun py-forward-try-block-bol ()
  "Goto beginning of line following end of ‘try-block’.

Return position reached, if successful, nil otherwise.
See also ‘py-down-try-block’: down from current definition to next beginning of ‘try-block’ below."
  (interactive)
  (py--beginning-of-line-form (py-forward-try-block)))

;; python-components-forward-forms.el ends here
(provide 'python-components-forward-forms)
