* Welcome to Python Development Emacs Environment - PDEE

Originating from Grabriele Lanaros's
`emacs-for-python', PDEE collects and customizes
resources reachable from Emacs to obtain a really
modern and exciting (yet stable) way to edit Python
files.

Configurations are similar to emacs-starter-kit,
(instruction below).

** Features 

Coming with a bunch of files, PDEE makes it easy to run
what's needed.

*** Python Related

    - Ropemacs (Custom) : A refactoring library
    - Auto Completion with rope (Custom) : Tested to work well with Rope
    - Flymake + pyflakes (Custom): Highlight errors on the fly, improved
      from the standard version
    - Virtualenv : Original, In-development tool for using virtualenv in
      Emacs.
    - Custom Yasnippet Snippets
    - Cython Mode: a mode for highlighting cython files
    - Choice of available basic python-modes.

*** Editing Packages
    
    - Auto Completion: Auto complete anything in Emacs
    - Yasnippet: Snippets on steroids
    - Parentheses pairing (Custom): Bug-free parentheses pairing using
      skeletons.
    - smart-operator: Automatically adds spaces around arithmetic operators.

*** Configurations

    - ido activation
    - ibuffer instead of buffer menu
    - eshell configuration

*** Keybindings

    - Copy-Cut-Paste from clipboard with Super-C Super-X Super-V    
    - Calc Mode remapping to M-c
    - M-Tab remapped to C-Tab to avoid collisions with the desktop
      manager

** Installation

Put the emacs-for-python directory in .emacs.d directory (or any
other), the add this line in your .emacs, it will enable all the
features of emacs-for-python package (editing configuration,
keybindings, python stuff etc...)

: (load-file "/path/to/emacs-for-python/epy-init.el")

You may want to enable only some of the features provided by
emacs-for-python, in this case just enable some of them:

: (add-to-list 'load-path "path/to/emacs-for-python/") ;; tell where to load the various files
: (require 'epy-setup) ;; It will setup other loads, it is required!
: (require 'epy-python) ;; If you want the python facilities [optional]
: (require 'epy-completion) ;; If you want the autocompletion settings [optional]
: (require 'epy-editing) ;; For configurations related to editing [optional]
: (require 'epy-bindings) ;; For my suggested keybindings [optional]

For further information and usage suggestions check:

- [[https://github.com/gabrielelanaro/emacs-for-python/wiki]]
- [[http://wiki.github.com/gabrielelanaro/emacs-for-python/workflow]]

There is another nice tutorial on how to install emacs-for-python
here:
[[http://maddemcode.com/python/emacs-and-python-the-definitive-answer/]] 

*** Configuring the _flymake_ checker
New in version 0.3:
I changed the way you configure your checkers, now there is no
predefined checker and you have to configure it by your own.

The good news is that it is extremely simple to configure your own
command, for example to configure the pyflakes checker install it and
put in your customization file (.emacs):

: (epy-setup-checker "pyflakes %f")

Obviously you can substitute the ``"pyflakes %f"`` with wathever you
want, you just have to keep in mind that ``%f`` will be substituted
with the file which is being checked.

*** Adding the django snippets
The django snippets comes as an option, you can load them using:

: (epy-django-snippets)

As a command using M-x or putting it in your .emacs.
*** ipython integration 
Ipython can be integrated with python-mode. Clicking on the
Python->Start interpreter menu entry will spawn an ipython shell
instead of a python one. To enable the feature put this line in your .emacs:

: (epy-setup-ipython)

** Installation with emacs-starter-kit
I've built up a little fork of emacs starter kit that is greatly
integrated with emacs-for-python, it seems the best solution to me!

The repo is at this address: [[http://github.com/gabrielelanaro/emacs-starter-kit]]

Remember that customization to emacs-starter-kit are done to a
custom.el file, and so you can substitute your distribution of
emacs-starter-kit and you have to copy just your customization file.

** License

This is mostly a distribution with some little tweaks, with respect of
the licenses, my tweaks are distributed according to the term of the
GNU GPL license, described in the file COPYING.

Generally each file has its own license and copyright notice (most, if
not all of packages are GPL), the license of rope (GPL) is in
rope-dist/COPYING.

